Add files via upload
NEETCOINTeam/NEETCOIN pull request #12
Opened 2018-02-01 05:11 UTC by kazu3kazu3

Correct copyright

2018-02-05 10:44 UTC, ghost approved these changes

2018-02-05 10:46 UTC, ghost requested changes
Please change the commit message to explain what you do.

2018-02-06 03:41 UTC, NEETCOINProject approved these changes
Thank you.

2018-02-06 04:42 UTC, ghost approved these changes

2018-02-06 04:45 UTC, shirako-jp commented
![z](https://user-images.githubusercontent.com/34421494/35842212-0f1087fc-0b44-11e8-8eec-a5b391432b59.png)

2018-02-07 16:08 UTC, merged